services:
  app:
    build:
      context: ./web
      dockerfile: Dockerfile
      secrets:
        - env
    container_name: ortamnasil
    restart: unless-stopped
    ports:
      - "127.0.0.1:3003:3000"
    env_file:
      - ./web/.env
    environment:
      - NODE_ENV=production
    extra_hosts:
      - "host.docker.internal:host-gateway"

secrets:
  env:
    file: ./web/.env
